name: First workflow

on: # on event
  push: # event
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build: #job name
    environment: prod #if job use environment , create environment on github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Write redirect file
        run: cd dist && echo '/*  /index.html  200' > _redirects
      - name: Deploy to netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'
          production-branch: main
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
  otherJob:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello there!"
  lastJob:
    runs-on: ubuntu-latest
    steps:
      - name: Good bye
        run: echo "Bye..."

